name: "Newman Demo"
on:[push, pull_request]

jobs: 
  build:
    run-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run Restful Booker BVT.postman_collection.json -e Production.environment.json
        
